article/urls.py
from django.urls import path
from . import views
# 正在部署的應用的名稱
app_name = 'article'

urlpatterns = [
    #文章列表
    path('article-list/', views.article_list, name='article_list'),
    # 文章詳情
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    # 寫文章
    path('article-create/', views.article_create, name='article_create'),

    # 安全刪除文章
    path(
        'article-safe-delete/<int:id>/',
        views.article_safe_delete,
        name='article_safe_delete'
    ),
    
    # 更新文章
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from article.views import article_list

urlpatterns = [
    path('admin/', admin.site.urls),
   
    #主頁
    path('', article_list, name='home'),
    
    path('article/', include('article.urls', namespace='article')),
    
    # 用戶管理
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    
    # 評論
    path('comment/', include('comment.urls', namespace='comment')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用戶登入
    path('login/', views.user_login, name='login'),
    # 用戶退出
    path('logout/', views.user_logout, name='logout'),
    
    # 用戶註冊
    path('register/', views.user_register, name='register'),
    
    # 用戶刪除
    path('delete/<int:id>/', views.user_delete, name='delete'),
    
     # 用戶信息
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# 用戶擴展信息
class Profile(models.Model):
    
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    # 頭像
    avatar = models.ImageField(upload_to='avatar/%Y%m%d/', blank=True)
    # 簡介
    bio = models.TextField(max_length=100, blank=True)

    def __str__(self):
        return 'user {}'.format(self.user.username)
    

userprofile/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

# 登錄表單，繼承了 forms.Form 類
class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


# 註冊用戶表單
class UserRegisterForm(forms.ModelForm):
    # 覆寫 User 的密碼
    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'email')

    # 對兩次輸入的密碼是否一致進行檢查
    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            raise forms.ValidationError("密碼輸入不一致,請重試。")


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('avatar', 'bio')

userprofile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from .forms import UserLoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import ProfileForm
from .models import Profile



def user_login(request):
    if request.method == 'POST':
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            # .cleaned_data 清洗出合法數據
            data = user_login_form.cleaned_data
            # 檢驗帳號、密碼是否正確匹配數據庫中的某個用戶
            # 如果均匹配則返回這個 user 對象
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                # 將用戶數據保存在 session 中，即實現了登入動作
                login(request, user)
                return redirect("article:article_list")
            else:
                return HttpResponse("帳號或密碼輸入有誤。請重新輸入~")
        else:
            return HttpResponse("帳號或密碼輸入不合法")
    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context = { 'form': user_login_form }
        return render(request, 'userprofile/login.html', context)
    else:
        return HttpResponse("請使用GET或POST請求數據")
    

# 用戶退出
def user_logout(request):
    logout(request)
    return redirect("article:article_list")

from .forms import UserLoginForm, UserRegisterForm

# 用戶註冊
def user_register(request):
    if request.method == 'POST':
        user_register_form = UserRegisterForm(data=request.POST)
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            # 設置密碼
            new_user.set_password(user_register_form.cleaned_data['password'])
            new_user.save()
            # 保存好數據後立即登入並返回blog列表頁面
            login(request, new_user)
            return redirect("article:article_list")
        else:
            return HttpResponse("註冊表單輸入有誤。請重新輸入~")
    elif request.method == 'GET':
        user_register_form = UserRegisterForm()
        context = { 'form': user_register_form }
        return render(request, 'userprofile/register.html', context)
    else:
        return HttpResponse("請使用GET或POST請求數據")


@login_required(login_url='/userprofile/login/')
def user_delete(request, id):
    if request.method == 'POST':
        user = User.objects.get(id=id)
        # 驗證登錄用戶、待刪除用戶是否相同
        if request.user == user:
            #退出登錄，刪除數據並返回博客列表
            logout(request)
            user.delete()
            return redirect("article:article_list")
        else:
            return HttpResponse("你沒有刪除操作的權限。")
    else:
        return HttpResponse("僅接受post請求。")
    
# 編輯用戶信息
@login_required(login_url='/userprofile/login/')
def profile_edit(request, id):
    user = User.objects.get(id=id)
    
    if Profile.objects.filter(user_id=id).exists():
        profile = Profile.objects.get(user_id=id)
    else:
        profile = Profile.objects.create(user=user)


    if request.method == 'POST':
        # 驗證修改數據者，是否為用戶本人
        if request.user != user:
            return HttpResponse("你沒有權限修改此用戶信息。")

        profile_form = ProfileForm(request.POST, request.FILES)
        if profile_form.is_valid():
            # 取得清洗後的合法數據
            profile_cd = profile_form.cleaned_data
            profile.bio = profile_cd['bio']
            if 'avatar' in request.FILES:
                profile.avatar = profile_cd["avatar"]
            profile.save()
            # 帶參數的 redirect()
            return redirect("userprofile:edit", id=id)
        else:
            return HttpResponse("註冊表單輸入有誤。請重新輸入~")

    elif request.method == 'GET':
        profile_form = ProfileForm()
        context = { 'profile_form': profile_form, 'profile': profile, 'user': user }
        return render(request, 'userprofile/edit.html', context)
    else:
        return HttpResponse("請使用GET或POST請求數據")

templates/userprofile/edit.html
{% extends "base.html" %} {% load static %}
{% block title %} 用戶信息 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <div class="col-md-4">用戶名: {{ user.username }}</div>
            <br>
            {% if profile.avatar %}
                <div class="col-md-4">頭像</div>
                <img src="{{ profile.avatar.url }}" style="max-width: 20%; border-radius: 15%;" class="col-md-4">
            {% else %}
                <h5 class="col-md-4">暫無頭像</h5>
            {% endif %}
            <br>
            <form method="post" action="." enctype="multipart/form-data"> 
                {% csrf_token %}
                <!-- avatar -->
                <div class="form-group col-md-4" >
                    <label for="avatar">上傳頭像</label><br>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>
                {% csrf_token %}
                <!-- bio -->
                <div class="form-group col-md-4">
                    <label for="bio">簡介</label>
                    <textarea type="text" class="form-control" id="bio" name="bio" rows="12">{{ profile.bio }}</textarea>
                </div>
                <br>
                <!-- 提交按鈕 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/userprofile/login.html
{% extends "base.html" %} {% load static %}
{% block title %} 登入 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <h5>還沒有帳號？</h5>
            <h5>點擊<a href='{% url "userprofile:register" %}'>註冊賬號</a>加入我們吧！</h5>
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <!-- 帳號 -->
                <div class="form-group">
                    <label for="username">帳號</label>
                    <input type="text" class="form-control" id="username" name="username">
                </div>
                <!-- 密碼 -->
                <div class="form-group">
                    <label for="password">密碼</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <!-- 提交按鈕 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/userprofile/register.html
{% extends "base.html" %} {% load static %}
{% block title %} 登入 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row justify-content-center" >
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <!-- 帳號 -->
                <div class="form-group col-md-4">
                    <label for="username">帳號</label>
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>
                <!-- 郵件 -->
                <div class="form-group col-md-4">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" id="email" name="email">
                </div>
                <!-- 密碼 -->
                <div class="form-group col-md-4">
                    <label for="password">設置密碼</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <!-- 確認密碼 -->
                <div class="form-group col-md-4">
                    <label for="password2">確認密碼</label>
                    <input type="password" class="form-control" id="password2" name="password2" required>
                </div>
                <!-- 提交按鈕 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}