article/urls.py
from django.urls import path
from . import views
# 正在部署的應用的名稱
app_name = 'article'

urlpatterns = [
    #文章列表
    path('article-list/', views.article_list, name='article_list'),
    # 文章詳情
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    # 寫文章
    path('article-create/', views.article_create, name='article_create'),

    # 安全刪除文章
    path(
        'article-safe-delete/<int:id>/',
        views.article_safe_delete,
        name='article_safe_delete'
    ),
    
    # 更新文章
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from article.views import article_list

urlpatterns = [
    path('admin/', admin.site.urls),
   
    #主頁
    path('', article_list, name='home'),
    
    path('article/', include('article.urls', namespace='article')),
    
    # 用戶管理
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    
    # 評論
    path('comment/', include('comment.urls', namespace='comment')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用戶登入
    path('login/', views.user_login, name='login'),
    # 用戶退出
    path('logout/', views.user_logout, name='logout'),
    
    # 用戶註冊
    path('register/', views.user_register, name='register'),
    
    # 用戶刪除
    path('delete/<int:id>/', views.user_delete, name='delete'),
    
     # 用戶信息
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zh-han">

<head>
   
    <meta charset="utf-8">
  
    <title>{% block title %}{% endblock %}</title>
   
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    
   
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">

    <link 
      rel="stylesheet" 
      href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.14.0/css/all.min.css"
    >
    
    
</head>

<body>
   
    {% include 'header.html' %}
    <div id = "wrapper">
      {% block content %}{% endblock content %}
      <div id = "push"></div>
    </div>
    
    {% include 'footer.html' %}
   
    
    <script src="{% static 'jquery/jquery 3.7.1.js' %}"></script>
  
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>
   
    
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
   
    <script src="{% static 'bootstrap/js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'layer/layer.js' %}"></script>
    
    <style>
      html, body {
          height: 100%;
          margin: 0;
      }

      #wrapper {
          min-height: 100%;
          margin-bottom: -60px;
      }

      #footer,
      #push {
          height: 60px;
      }
  </style>
</body>

</html>

templates/footer.html
{% load static %}
<!-- Footer -->
<head>
    <link 
      rel="stylesheet" 
      href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.14.0/css/all.min.css"
    >
</head>
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        
        <p class="m-0 text-center text-white">Made by 抹茶山背包 &copy; 2023</p>
        
    </div>
</footer>

templates/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
   
    <div class="container" style = "height:50px">
        <a href="{% url 'article:article_list' %}"><img src= "{% static "image/logo.png" %}" style = "height: 120px; width:120px"class="rounded float-start"></a>
        <a href="{% url 'article:article_list' %}"> <h3 style = "color:white; margin-left:-610px; margin-top:8px;" class="rounded float-start">隨筆窩</h3></a>

        <div>
            <ul class="navbar-nav">
            
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_list' %}" style = "color:white">文章</a>
                </li>
                
              
                {% if user.is_authenticated %}
                <!-- 如果用戶已經登入，則顯示用戶名下拉框 -->
                <div class="dropdown">
                    <a
                        class="btn btn-secondary dropdown-toggle"
                        href="#"
                        role="button"
                        id="dropdownMenuLink"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                    >
                        {{ user.username }}
                    </a>

                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <li>
                            <a class="dropdown-item" href="#" onclick="user_delete()">刪除用戶</a>
                            <a class="dropdown-item" href='{% url "userprofile:logout" %}'>
                                退出登入
                            </a>
                            <a class="dropdown-item" href="{% url 'article:article_create' %}">
                                寫文章
                            </a>
                            <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>個人信息</a>
                        </li>
                    </ul>
                </div>
                <!-- 如果用戶未登入，則顯示 “登入” -->
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userprofile:login' %}">登入</a>
                </li>

                {% endif %}
            </ul>
        </div>
    </div>
    {% if user.is_authenticated %}
    <form
        style="display: none"
        id="user_delete"
        action="{% url 'userprofile:delete' user.id %}"
        method="POST"
    >
        {% csrf_token %}
        <button type="submit">發送</button>
    </form>
    <script>
        function user_delete() {
            // 调用layer弹窗组件
            layer.open({
                title: '確認刪除',
                content: '確認刪除用戶資料嗎？',
                yes: function (index, layero) {
                    $('form#user_delete button').click();
                    layer.close(index);
                },
            });
        }
    </script>
    {% endif %}
</nav>