article/urls.py
from django.urls import path
from . import views
# 正在部署的應用的名稱
app_name = 'article'

urlpatterns = [
    #文章列表
    path('article-list/', views.article_list, name='article_list'),
    # 文章詳情
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    # 寫文章
    path('article-create/', views.article_create, name='article_create'),

    # 安全刪除文章
    path(
        'article-safe-delete/<int:id>/',
        views.article_safe_delete,
        name='article_safe_delete'
    ),
    
    # 更新文章
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # 發表評論
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from article.views import article_list

urlpatterns = [
    path('admin/', admin.site.urls),
   
    #主頁
    path('', article_list, name='home'),
    
    path('article/', include('article.urls', namespace='article')),
    
    # 用戶管理
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    
    # 評論
    path('comment/', include('comment.urls', namespace='comment')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用戶登入
    path('login/', views.user_login, name='login'),
    # 用戶退出
    path('logout/', views.user_logout, name='logout'),
    
    # 用戶註冊
    path('register/', views.user_register, name='register'),
    
    # 用戶刪除
    path('delete/<int:id>/', views.user_delete, name='delete'),
    
     # 用戶信息
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
# timezone 用於處理時間相關事務。
from django.utils import timezone
from django.urls import reverse
from PIL import Image


class ArticleColumn(models.Model):
    """
    分類的 Model
    """
    # 分類的標題
    title = models.CharField(max_length=100, blank=True)
    # 創建時間
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

# Blog文章數據模型
class ArticlePost(models.Model):
    # 文章作者。參數 on_delete 用於指定數據刪除的方式，避免兩個關聯表的數據不一致
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    # 文章標題
    title = models.CharField(max_length=100)

    # 文章正文。保存大量文本使用 TextField
    body = models.TextField()

    # 文章創建時間。參數 default=timezone.now 指定其在創建數據時將默認寫入當前的時間
    created = models.DateTimeField(default=timezone.now)

    # 文章更新時間。參數 auto_now=True 指定每次數據更新時自動寫入當前時間
    updated = models.DateTimeField(auto_now=True)
    
    # 文章分類的 “一對多” 外鍵
    column = models.ForeignKey(
        ArticleColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article'
    )
    # 文章標題圖
    avatar = models.ImageField(upload_to='article/%Y%m%d/', blank=True)

    
    # 瀏覽數
    total_views = models.PositiveIntegerField(default=0)
    class Meta:
        # ordering 指定模型返回的數據的排列順序
    	# '-created' 表明數據應該以倒序排列
        ordering = ('-created',)
        
    def __str__(self):
        # 將文章標題返回
        return self.title
    
    # 獲取文章地址
    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])
    
    # 保存時處理圖片
    def save(self, *args, **kwargs):
        # 調用原有的 save() 的功能
        article = super(ArticlePost, self).save(*args, **kwargs)

        # 固定寬度縮放圖片大小
        if self.avatar and not kwargs.get('update_fields'):
            image = Image.open(self.avatar)
            (x, y) = image.size
            new_x = 400
            new_y = int(new_x * (y / x))
            resized_image = image.resize((new_x, new_y), Image.ANTIALIAS)
            resized_image.save(self.avatar.path)

        return article
    


    

   

article/forms.py
from django import forms
from .models import ArticlePost

# 寫文章的表單類
class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指明數據模型來源
        model = ArticlePost
        # 定義表單包含的字段
        fields = ('title', 'body','avatar')

article/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import ArticlePost
# 引入定義的ArticlePostForm表單類
from .forms import ArticlePostForm
# 引入User模型
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
import markdown
from django.core.paginator import Paginator
from django.db.models import Q
from comment.models import Comment
from .models import ArticleColumn

# 文章列表
def article_list(request):
    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')
   
    # 初始化查詢集
    article_list = ArticlePost.objects.all()

    # 搜詢查詢集
    if search:
        article_list = article_list.filter(
            Q(title__icontains=search) |
            Q(body__icontains=search)
        )
    else:
        # 將 search 參數重置為空
        search = ''

    # 分類查詢集
    if column is not None and column.isdigit():
        article_list = article_list.filter(column=column)

   
    # 查詢集排序
    if order == 'total_views':
        # 按熱度排序文章
        article_list = article_list.order_by('-total_views')

    paginator = Paginator(article_list, 3)
    page = request.GET.get('page')
    articles = paginator.get_page(page)

    context = {'articles': articles, 'order': order, 'search': search, 'column': column,
               }

    return render(request, 'article/list.html', context)

# 文章詳情
def article_detail(request, id):
    # 取出相應的文章
    article = ArticlePost.objects.get(id=id)
    # 取出文章評論
    comments = Comment.objects.filter(article=id)
    # 瀏覽量 +1
    article.total_views += 1
    article.save(update_fields=['total_views'])

    md = markdown.Markdown(
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ]
    )
    article.body = md.convert(article.body)

    context = {'article': article, 'toc': md.toc, 'comments': comments}
    return render(request, 'article/detail.html', context)

# 寫文章的view


@login_required(login_url='/userprofile/login/')
def article_create(request):
    # 判斷用戶是否提交數據
    if request.method == "POST":
        article_post_form = ArticlePostForm(request.POST, request.FILES)
       
        # 判斷提交的數據是否滿足模型的要求
        if article_post_form.is_valid():
            # 保存數據，但暫時不提交到數據庫中
            new_article = article_post_form.save(commit=False)
            # 指定目前登入的用戶為作者
            new_article.author = User.objects.get(id=request.user.id)

            if request.POST['column'] != 'none':
                new_article.column = ArticleColumn.objects.get(
                    id=request.POST['column'])
            # 將新文章保存到數據庫中
            new_article.save()

            article_post_form.save_m2m()

            # 完成後返回到文章列表
            return redirect("article:article_list")
        # 如果數據不合法，返回錯誤信息
        else:
            return HttpResponse("表單內容有誤，請重新填寫。")
    # 如果用戶請求獲取數據
    else:
        # 創建表單類實例
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()

        # 賦值上下文
        context = {'article_post_form': article_post_form, 'columns': columns}
        # 返回模板
        return render(request, 'article/create.html', context)

# 安全刪除文章


@login_required(login_url='/userprofile/login/')
def article_safe_delete(request, id):
    if request.method == 'POST':
        article = ArticlePost.objects.get(id=id)
        article.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse("僅允許post請求")

# 更新文章


@login_required(login_url='/userprofile/login/')
def article_update(request, id):
    """
    更新文章的視圖函數
    通過POST方法提交表單,更新titile、body字段
    GET方法進入初始表單頁面
    id: 文章的 id
    """

    # 獲取需要修改的具體文章對象
    article = ArticlePost.objects.get(id=id)
    # 過濾非作者的用户
    if request.user != article.author:
        return HttpResponse("抱歉，你無權修改这篇文章。")

    # 判斷用戶是否為 POST 提交表單數據
    if request.method == "POST":
        # 將提交的數據賦值到表單實例中
        article_post_form = ArticlePostForm(data=request.POST)
        # 判斷提交的數據是否滿足模型的要求
        if article_post_form.is_valid():
            # 保存新寫入的 title、body 數據並保存
            article.title = request.POST['title']
            article.body = request.POST['body']
            if request.POST['column'] != 'none':
                article.column = ArticleColumn.objects.get(
                    id=request.POST['column'])
            else:
                article.column = None
                
            if request.FILES.get('avatar'):
                article.avatar = request.FILES.get('avatar')
            article.save()
            
            # 完成後返回到修改後的文章中。需傳入文章的 id 值
            return redirect("article:article_detail", id=id)
        # 如果數據不合法，返回錯誤信息
        else:
            return HttpResponse("表單內容有誤，請重新填寫。")

    # 如果用戶 GET 請求獲取數據
    else:
        # 創建表單類實例
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        # 賦值上下文，將 article 文章對象也傳遞進去，以便提取舊的內容
        context = {'article': article, 'article_post_form': article_post_form,
                   'columns': columns, }
        # 將響應返回到模板中
        return render(request, 'article/update.html', context)

templates/article/create.html
{% extends "base.html" %} {% load static %}

{% block title %} 寫文章 {% endblock title %}

{% block content %}

<!-- 文章表單 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表單 -->
            <form method="post" action="." enctype="multipart/form-data">
                <!-- Django中需要POST數據的地方都必須有csrf_token -->
                {% csrf_token %}
                <!-- 文章標題圖 -->
                <div class="form-group">
                    <label for="avatar">標題圖</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>
                <!-- 文章標題 -->
                <div class="form-group">
                    <label for="title">文章標題</label>
                    <input type="text" class="form-control" id="title" name="title">
                </div>

                 <!-- 文章分類 -->
                <div class="form-group">
                    <label for="column">分類</label>
                    <select class="form-control" 
                            id="column" 
                            name="column"
                    >
                        <option value="none">請選擇分類..</option>
                    {% for column in columns %}
                        <option value="{{ column.id }}">{{column}}</option>
                    {% endfor %}
                    </select>
                </div>

                
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本區域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <br>
                <!-- 提交按鈕 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/article/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    文章詳情
{% endblock title %}


{% block content %}

<!-- 文章詳情 -->
<div class="container">
    <div class="row">
        <!-- 標題及作者 -->
        <div class="col-9">
            <h1 class="mt-4 mb-4">{{ article.title }}</h1>
            <div class="alert alert-success">
                <div>
                作者：{{ article.author }}
                {% if user == article.author %}
                    <a href="#" onclick="confirm_safe_delete()">删除文章</a>
                    <form 
                    style="display:none;" 
                    id="safe_delete"
                    action="{% url 'article:article_safe_delete' article.id %}" 
                    method="POST"
                    >
                    {% csrf_token %}
                    <button type="submit">發送</button>
                    </form>
                    <a href="{% url "article:article_update" article.id %}">編輯文章</a>
                {% endif %}
                </div>
                <div>
                瀏覽：{{ article.total_views }}
                </div>
            </div>
       

            <!-- 文章正文 -->
            <div class="col-12">
                <p>{{ article.body|safe }}</p>
            </div>
        
         <!-- 發表評論 -->
        <hr>
        {% if user.is_authenticated %}
            <div>
                <form 
                    action="{% url 'comment:post_comment' article.id %}" 
                    method="POST"
                >
                {% csrf_token %}
                    <div class="form-group">
                        <label for="body">
                            <strong>
                                我也要發言：
                            </strong>
                        </label>
                        <textarea 
                            type="text" 
                            class="form-control" 
                            id="body" 
                            name="body" 
                            rows="2"></textarea>
                    </div>
                    <br>
                    <!-- 提交按鈕 -->
                    <button type="submit" class="btn btn-primary ">發送</button>                    
                </form>
            </div>
            <br>
        {% else %}
            <br>
            <h5 class="justify-content-center">
                請<a href="{% url 'userprofile:login' %}">登入</a>才能評論
            </h5>
            <br>
        {% endif %}



        <!-- 顯示評論 -->
        <h4>共有{{ comments.count }}條評論</h4>
        <div>
            {% for comment in comments %}
                <hr>
                <p>
                    <strong style="color: pink">
                        {{ comment.user }}
                    </strong> 於 
                    <span style="color: green">
                        {{ comment.created|date:"Y-m-d H:i:s" }}
                    </span> 時說：
                </p>
                <pre style="font-family: inherit; font-size: 1em;">
{{ comment.body }}</pre>
            {% endfor %}
        </div>
    </div>
        <!-- 文章目錄 -->
        <div class="col-3 mt-4" id="sidebar" class="sidebar">
            <div class="sidebar__inner">
                <h4><strong>目錄</strong></h4>
                <hr>
                <div>
                    {{ toc|safe }}
                </div>
            </div>
        </div>
       
    </div>
</div>


<script>
    // 刪除文章的函數
    function confirm_safe_delete() {
        // 調用layer彈窗組件
        layer.open({
            title: "確認删除",
            content: "確認刪除這篇文章嗎？",
            // 點擊確定按鈕後調用的回調函數
            yes: function(index, layero) {
                $('form#safe_delete button').click();
                layer.close(index);
            }
        })
    }
</script>
{% endblock content %}

templates/article/list.html
{% extends "base.html" %} 
{% include 'back_to_top_func.html' %}
{% load static %}
{% block title %} 
首頁 
{% endblock title %} 
{% block content %}


<div class="container" >
    <br>
    <!-- 麵包屑導航 -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?search={{ search }}&column={{ column }}">
                    最新
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?order=total_views&search={{ search }}&column={{ column }}">
                    最熱門
                </a>
            </li>
        </ol>
    </nav>
    <!-- 搜尋欄 -->
    <div class="row">
        <div class="col-auto mr-auto">
            <form class="form-inline" >
                <input type="text" 
                    class="form-control mb-2 mr-sm-2" 
                    name="search" 
                    placeholder="搜索文章..." 
                    required
                >
            </form>
        </div>
    </div>

    <!-- 搜尋提示 -->
    {% if search %}
    {% if articles %}
        <h4><span style="color: red">"{{ search }}"</span>的搜尋結果如下：</h4>
        <hr>        
    {% else %}
        <h4>暫無<span style="color: red">"{{ search }}"</span>有關的文章。</h4>
        <hr>
    {% endif %}
    
    {% endif %}

    <!-- 列表循環 -->
    <div class="row mt-2">
        {% for article in articles %}
            <!-- 文章內容 -->
            <!-- 標題圖 -->
            {% if article.avatar %}
            <div class="col-3">
                <img src="{{ article.avatar.url }}" 
                    alt="avatar" 
                    style="max-width:100%;max-height:90%;border-radius: 50px"
                >
            </div>
            {% endif %}
            
            <div class="col">
                <!-- 分類 -->
                {% if article.column %}
                <a  role="button" 
                    href="{% url 'article:article_list' %}?column={{ article.column.id }}"
                    class="btn btn-sm mb-2
                            {% if article.column.title == '技術' %}
                                btn-primary
                            {% elif article.column.title == '旅遊' %}
                                btn-success
                            {% elif article.column.title == '其他' %}
                                btn-danger
                            {% elif article.column.title == '美食' %}
                                btn-warning
                            {% elif article.column.title == '3C' %}
                                btn-info
                            {% endif %}
                        "
                    >
                        {{ article.column }}
                      </a>
                {% endif %}
              
               
                <!-- 標題 -->
                <h4>
                    <b>
                        <a href="{% url 'article:article_detail' article.id %}"
                        style="color: black;" 
                        >
                            {{ article.title }}
                        </a>
                    </b>
                </h4>
                <!-- 摘要 -->
                <div>
                    <p style="color: gray;">
                        {{ article.body|slice:'100' }}...
                    </p>
                </div>
                <!-- 駐腳 -->
                <p>
                    <!-- 附加信息 -->
                    <span style="color: green;">
                        <i class="fas fa-eye" style="color: lightskyblue;"></i>
                        {{ article.total_views }} 瀏覽&nbsp;&nbsp;&nbsp;
                    </span>
                    <span style="color: blue;">
                        <i class="fas fa-comments" style="color: yellowgreen;"></i>
                        {{ article.created|date:'Y-m-d' }} 發佈&nbsp;&nbsp;&nbsp;
                    </span>
                    <span style="color: darkred;">
                        <i class="fas fa-clock" style="color: pink;"></i>
                        {{ article.updated|date:'Y-m-d' }} 更新
                    </span>
                </p>
                
            </div>
            
            <hr style="width: 100%;"/>
            
        {% endfor %}
    </div>




    <div class="pagination" >
        <div class="m-auto">
            <span class="step-links">
                <!-- 如果不是第一頁，則顯示上翻按鈕 -->
                {% if articles.has_previous %}
                <a href="?page=1&order={{ order }}&search={{ search }}&column={{ column }}" class="btn btn-success">&laquo; 1</a>
                <span>...</span>
                <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}&column={{ column }}" 
                       class="btn btn-secondary"
                    >
                    {{ articles.previous_page_number }}
                </a>
                {% endif %}

                <!-- 當前頁面 -->
                <span class="current btn btn-danger btn-lg">{{ articles.number }}</span>

                <!-- 如果不是最末頁，則顯示下翻按鈕 -->
                {% if articles.has_next %}
                <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}&column={{ column }}"
                class="btn btn-secondary"
             >
                    {{ articles.next_page_number }}
                </a>
                <span>...</span>
                <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}&column={{ column }}"
                class="btn btn-success"
             >   
                    {{ articles.paginator.num_pages }} &raquo;
                </a>
                {% endif %}
            </span>
        </div>
    </div>
   
</div>
{% endblock content %}

templates/article/update.html
{% extends "base.html" %} {% load static %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                 <!-- 文章標題圖 -->
                 <div class="form-group">
                    <label for="avatar">標題圖</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>

                <div class="form-group">
                    <label for="title">文章標題</label>
                    <!-- 在 value 屬性中指定文本框的初始值為舊的內容，即 article 對象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                
                 <!-- 文章分類 -->
                <div class="form-group">
                    <label for="column">欄目</label>
                    <select class="form-control" 
                            id="column" 
                            name="column"
                    >
                            <option value="none">請選擇欄目..</option>
                        {% for column in columns %}
                            <option value="{{ column.id }}"
                                {% if column.id == article.column.id %}
                                    selected
                                {% endif %}
                            >
                                {{ column }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
               
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}